Added back buttons in ProfileActivity and AboutActivity
PEC-CSS/MovieDroid pull request #106
Opened 2022-10-21 06:12 UTC by VSen910

## Description

Added an icon for the back button to use in both activities and set an onClickListener to both. 

## Issue Resolved

Fixes #103 

## Screenshots 
![Screenshot 2022-10-21 113749](https://user-images.githubusercontent.com/104011412/197124581-249ab4c3-952b-45cc-8d3e-0ec3f0f4ad8b.jpg)
![Screenshot 2022-10-21 113810](https://user-images.githubusercontent.com/104011412/197124589-5d8da487-ef2e-4883-8a98-aabf71a89436.jpg)

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

2022-10-21 18:13 UTC, ken1000minus7 requested changes
Hey @VSen910 , please remove changes made to the gradle files, they are not required 😇

2022-10-22 08:08 UTC, VSen910 commented
I've reverted the Gradle version back to the original one now

2022-10-22 10:35 UTC, ken1000minus7 approved these changes

2022-10-22 10:38 UTC, ken1000minus7 commented
Great work, thanks for your contribution ! 😄

2022-10-22 10:39 UTC, merged