added a piechart in profileactivity
PEC-CSS/MovieDroid pull request #143
Opened 2023-02-22 18:03 UTC by armaanbadhan

## Description

pie chart added which shows counts of different lists of user

## Issue Resolved

fixes #79 

## Screenshots 

<div>
<img src="https://user-images.githubusercontent.com/66007619/220715636-1514e5e1-ccfe-4714-92a7-010cb780a2c9.png" height=400>
<img src="https://user-images.githubusercontent.com/66007619/220715660-690f24e8-6741-4469-a5a3-3e53676a4665.png" height=400>
<img src="https://user-images.githubusercontent.com/66007619/220715678-daec274e-29f1-4fef-b876-7271da1a3690.png" height=400>
</div>
## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

2023-02-22 18:53 UTC, ken1000minus7 requested changes
Looks nice, gw,, small changes required though

2023-02-22 18:53 UTC, ken1000minus7 commented on app/src/main/res/layout/activity_profile.xml
> +        android:layout_height="135dp"
Use `sdp` instead of `dp` eberywhere

2023-02-22 18:53 UTC, ken1000minus7 commented on app/src/main/res/layout/activity_profile.xml
> +        android:layout_marginRight="10dp"
Here as well

2023-02-22 18:53 UTC, ken1000minus7 commented on app/src/main/res/layout/activity_profile.xml
> +            android:layout_width="135dp"
Here too

2023-02-22 18:53 UTC, ken1000minus7 commented on app/src/main/res/layout/activity_profile.xml
> +        android:layout_marginEnd="1dp"
aaaand here

2023-02-22 18:53 UTC, ken1000minus7 commented on app/src/main/res/layout/activity_profile.xml
> +        android:layout_marginEnd="1dp"
here here too too

2023-02-23 07:55 UTC, armaanbadhan commented
done!

2023-02-23 15:38 UTC, ken1000minus7 approved these changes
Lgtm gw

2023-02-23 15:38 UTC, merged