fix: text in home page cards
PEC-CSS/MovieDroid pull request #93
Opened 2022-10-12 14:28 UTC by V9vek

## Description

Fixed the text in the home page cards by making the text centered and adding ellipses when text gets long

## Issue Resolved

Fixes #92 

## Screenshots 

![img2](https://user-images.githubusercontent.com/40730402/195370052-9bc38e4e-ed15-43ff-b8ca-bd1cb4f0e8ec.jpg)

![img1](https://user-images.githubusercontent.com/40730402/195370147-12fadaab-c918-49a5-bb87-01494d548e88.jpg)

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

2022-10-12 17:30 UTC, ken1000minus7 requested changes
Great work @V9vek 😄 , a few changes are required, please go through them, once completed, your pr will be ready to be merged 😇

2022-10-12 17:30 UTC, ken1000minus7 commented on app/google-services.json
> +        {
You don't have to commit changes to this file, please remove these 😅

2022-10-12 17:30 UTC, ken1000minus7 commented on gradle/wrapper/gradle-wrapper.properties
>  distributionBase=GRADLE_USER_HOME
This isn't required, please remove it 😇

2022-10-12 17:37 UTC, V9vek commented on gradle/wrapper/gradle-wrapper.properties
>  distributionBase=GRADLE_USER_HOME
Sure

2022-10-12 17:47 UTC, V9vek commented
I have reverted those changes to previous code @ken1000minus7 
please take a look now and do let me know 😊

2022-10-13 07:27 UTC, ken1000minus7 approved these changes
Lgtm, thanks for your contribution 😄

2022-10-13 07:29 UTC, merged